# Generated by Django 2.2 on 2021-11-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20211106_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Папищик', 'verbose_name_plural': 'БРАТВА ПАПИЩИКОВ!!!'},
        ),
    ]
