# Generated by Django 2.2 on 2021-11-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20211106_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
